### ISSUE TITLE
Skip tests for a particular variant?

### ISSUE THREAD

**Issue by emilesvt** [robolectric/robolectric-gradle-plugin#103]
Is there a way to skip tests for a specific variant(s)?

The reason I ask is, we have a variant that we can deploy to our devices for mocked scenarios.  This is mostly used by the developers when the backend is down.  We really don't care if the unit tests pass this particular variant, so we'd prefer to skip this variant all together to speed up the build process.

With that being said, it'd be nice if we could turn off/on the unit tests for a specific variant that would allow us to run those tests in a CI environment should we choose.

**Comment by jaredsburrows** [comment]
@emilesvt @naoyamakino 

Are you running a command similar to `gradlew test`?

Have you tried simply running against single variants? For example: `gradlew testFreeDebug testPaidDebug`?

**Comment by erd** [comment]
The plugin is being deprecated with the release of Robolectric 3.0. Closing open issues.
