### ISSUE TITLE
Robolectric library not found with NoClassDefFoundError for ShadowMediaMetadataRetriever 

### ISSUE THREAD

**Issue by mpost** [robolectric/robolectric-gradle-plugin#106]
I am currently running robolectric tests with the plugin at <code>0.13.2</code> and robolectric <code>2.4</code>. When trying to execute the tests on a freshly installed machine i experienced the problem that i get the following exception for all test:

<pre lang="java">
 java.lang.NoClassDefFoundError: Could not initialize class org.robolectric.shadows.ShadowMediaMetadataRetriever 
</pre>

Building the project is fine, it is only the test execution that fails. I have observed that the robolectric library is downloaded into <code>.gradle\caches\modules-2\files-2.1\org.robolectric\robolectric\2.4</code>.

Maybe the gradle plugin is trying to consume from the .m2 repository instead of from the gradle cache? Has anybody ever tried to move/rename his .m2 folder and run robolectric tests?

I have copied the .m2 directory from another machine to the new testing machine and the robolectric dependencies where found. So i question whether the gradle plugin really using the correct folder to find the robolectric library.

**Comment by erd** [comment]
> java.lang.NoClassDefFoundError: com/google/android/collect/Maps

This is actually a bug in robolectric core and has been fixed in 3.0-SNAPSHOT.
