### ISSUE TITLE
The existing "androidTest" sourceSet should not be (re-)used

### ISSUE THREAD

**Issue by sschuberth** [robolectric/robolectric-gradle-plugin#107]
Currently, Robolectric is hard-coded to use the existing "androidTest" sourceSet as provided by the Android Gradle plugin. By doing this, we cannot cleanly separate Robolectric unit test code from the "usual" functional test code (Ui Automator, Robotium, Espresso) anymore. It would be nice if Robolectric would be using a "unitTest" or "androidUnitTest" sourceSet instead, along with matching configurations. If backward compatibility needs to be maintained, then Robolectric should be configurable which sourceSet / configuration name to use, defaulting to the current "androidTest" name.

The overlapping use of "androidTest" between functional and unit tests is the main reason why we need to use the [android-unit-test](https://github.com/JCAndKSolutions/android-unit-test) Gradle plugin instead. However, that plugin has [other shortcomings](https://github.com/JCAndKSolutions/android-unit-test/issues/32).

**Comment by erd** [comment]
With #129, we piggyback on the Android Gradle plugin's support for unit tests (which has a separate scope for unit tests and integration tests).
