### ISSUE TITLE
java.lang.RuntimeException: Stub! with JSONObject after updating to 0.14.0

### ISSUE THREAD

**Issue by felipecsl** [robolectric/robolectric-gradle-plugin#112]
This used to work fine with the plugin version 0.13.0
Im on robolectric 2.4 and gradle 2.2 (same happens on gradle 2.1)
Please let me know what relevant parts of my build.gradle file I should provide to help debugging.

**Comment by jaredsburrows** [comment]
@felipecsl does this "stub" error only show up in Android Studio? Have you tried running via command line? `gradlew clean test`?

**Comment by felipecsl** [comment]
Sorry I'm not working anymore on the project that was causing this issue. I'll let you know if I see it again.
Thanks!

**Comment by jaredsburrows** [comment]
@felipecsl  Can we close this issue if you are not longer working on this project or not seeing that error anymore?

**Comment by felipecsl** [comment]
Fair enough!
