### ISSUE TITLE
0.14.+ Can not support android gradle plugin 1.0.0

### ISSUE THREAD

**Issue by carl1990** [robolectric/robolectric-gradle-plugin#120]
my gradle is 2.2.1
android plugin is 1.0.0
but there has a error:
The Android Gradle plugin 1.0.0 is not supported.

when will be support for android gradle plugin 1.0.0

**Comment by carl1990** [comment]
I was used  0.14.+ version ,update to version 0.14.1 and then work well now!
thank you

**Comment by dallasgutauckis** [comment]
The `README.md` should be updated to reflect this support (currently states it only supports `0.14.+`)

**Comment by jaredsburrows** [comment]
@carl1990  @dallasgutauckis  The `README.md` was recently updated.

    buildscript {
        dependencies {
            classpath 'com.android.tools.build:gradle:1.0.1'
            classpath 'org.robolectric:robolectric-gradle-plugin:0.14.1'
        }
    }

Also, I use Gradle `2.2.1`, Android Plugin `1.0.1` along with Robolectric `2.4` and Robolectric Plugin `0.14.1` and it works fine. Can we close this?

**Comment by ChristianBecker** [comment]
I'm pretty sure that this can be closed. The `README.md` is up-to-date with the most-current versions.
