### ISSUE TITLE
AAR dependencies do not work with any non-debug build type

### ISSUE THREAD

**Issue by jhansche** [robolectric/robolectric-gradle-plugin#122]
Issue #87 fixed the AAR dependencies issue for the `debug` build type, but any other (non-release) build type continues to show the problem.  @ChristianBecker suggested at square/assertj-android#129 that I should open a new issue here with a simplified test project that shows the behavior.  That test project can be found at jhansche/robotest-aar@d32f38a8c844eafd7e13e218319909872e86ec87

In this project, I have three build types:  debug, release, and internal.  Internal is `initWith(release)`, but has `debuggable=true`.  The purpose is to go through our normal release flow (including Proguard), but maintain the debuggable flag, and keep internal logging in place.

The project includes an `androidTestCompile` dependency for assertj-android, which is packaged and released to Maven central as an AAR.  Running `:testDebug` works correctly, but `:testInternal` fails.

**Comment by erd** [comment]
This should be fixed in #129, since we piggy-back on the unit test support added in version 1.1.0 of the Android Gradle plugin.

**Comment by jrgonzalezg** [comment]
It seems that all issues related to this are now closed, but still AAR depedencies like assertj-android are not working properly. The compiler fails because it can not resolve the imports. This happens both using the latest stable (1.01) and the latest snapshot (1.1.0-SNAPSHOT) version of robolectric-gradle-plugin and the latest version of the android gradle plugin (1.1.3).

**Comment by ChristianBecker** [comment]
This is already fixed in the current codebase and will be released with a future release of the Android Gradle plugin. See https://code.google.com/p/android/issues/detail?id=140293 for further informations.

**Comment by jrgonzalezg** [comment]
Great! Thanks for the quick reply :)
