### ISSUE TITLE
Support for org.robolectric:robolectric:3.0-SNAPSHOT

### ISSUE THREAD

**Issue by pbibalan** [robolectric/robolectric-gradle-plugin#127]
I was wondering if the plugin currently supports org.robolectric:robolectric:3.0-SNAPSHOT? 
Here I can see it is mentioned

```
 // TODO: requires special build of robolectric right now. working on this...
    testCompile('org.robolectric:robolectric:2.4') {
        exclude module: 'classworlds'
        exclude module: 'commons-logging'
        exclude module: 'httpclient'
        exclude module: 'maven-artifact'
        exclude module: 'maven-artifact-manager'
        exclude module: 'maven-error-diagnostics'
        exclude module: 'maven-model'
        exclude module: 'maven-project'
        exclude module: 'maven-settings'
        exclude module: 'plexus-container-default'
        exclude module: 'plexus-interpolation'
        exclude module: 'plexus-utils'
        exclude module: 'wagon-file'
        exclude module: 'wagon-http-lightweight'
        exclude module: 'wagon-provider-api'
    }
```

I have reported an issue on robolectric main project regarding an issue I have but the issue might actually be cause by the plugin
https://github.com/robolectric/robolectric/issues/1536 

Thoughts?

**Comment by jhansche** [comment]
@pbibalan Why was this closed?  Did you resolve the issue somehow?

**Comment by pbibalan** [comment]
I thought it was resolved @jhansche but I started seeing it again on the CI servers. A workaround which I don't like is to download the robolectric-resources jar from 
```
https://oss.sonatype.org/content/groups/public/org/robolectric/robolectric-resources/3.0-SNAPSHOT/ 
```
and install manually 
```
mvn install:install-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.0-SNAPSHOT -Dclassifier=21 -Dpackaging=jar -Dfile=/path/to/file
```

I am not sure what the underlying problem is. Reopening the issue.

**Comment by erd** [comment]
This is an issue with Robolectric's travis build, not gradle plugin. Please comment on this issue instead: https://github.com/robolectric/robolectric/issues/1536.
