### ISSUE TITLE
Work gracefully with Android Gradle plugin 1.1.0

### ISSUE THREAD

**Issue by jhansche** [robolectric/robolectric-gradle-plugin#128]
This week Google released Android Gradle plugin 1.1.0-rc1, which has initial support for running unit tests, preparing to enable running unit tests within Android Studio.

As of now, applying the robolectric plugin collides with the Android plugin, because the `testCompile` configuration cannot be created <https://github.com/robolectric/robolectric-gradle-plugin/blob/master/src/main/groovy/org/robolectric/gradle/RobolectricPlugin.groovy#L26>:

    > Failed to apply plugin [id 'robolectric']
       > Cannot add a configuration with name 'testCompile' as a configuration with that name already exists.

Commenting out the apply plugin line allows it to continue, but without the plugin, none of the expected properties get set, so the TestRunner cannot find `AndroidManifest.xml`, which in turns makes it unable to find any of the project's resources.

**Comment by jhansche** [comment]
With 1.1.0-rc1, it's possible to basically skip creating and configuring all the `testCompileTask` and `testRunTask`, skip the `testCompile` configuration, and just throw in the `android.*` systemProperty lines and it mostly works using the built-in Android Gradle tasks.

The one thing that was missing for my case was that it's not copying the `src/test/resources/org.robolectric.Config.properties` file into the resulting classpath.  But if I copy the file from `src/test/resources/` into `build/intermediates/classes/test/debug/`, it works.

**Comment by erd** [comment]
I heard that Google was going to do something related to unit testing in 1.1.0, but I couldn't find any information on it. I'll see if I can check out the android gradle plugin code this weekend, and see if there's anything we need to do. I'd personally be happy if we could kill off this plugin and have robolectric work out of the box.

**Comment by mpost** [comment]
They are introducing a way to run tests on the local VM against a patched Android.jar. All native methods return default values and the final modifiers are removed. You can run those tests as regular unit tests. So from inside Android studio.

**Comment by jhansche** [comment]
@erd I have a local diff that accomplishes a rudimentary implementation that does not collide with Android's plugin (still falls back to existing behavior for <1.1.0), but not sure that I'm confident enough to submit it as a PR.  I have a feeling it wouldn't pass muster, and not convinced that I have the time necessary to do a proper implementation that would.  But I can post a diff to gist if you'd like to see the 30-minute hack just to see it work.

I'm abandoning my attempt to update to 1.1.0 for now though, because the resources not getting copied to the classpath makes it difficult to get Config.properties and some other resource files (we have `.json` files used to emulate API responses for certain tests that get loaded from the ClassLoader).  But that would need to be addressed in the Android Gradle plugins compile task.

**Comment by tallen1983** [comment]
I really hope you can make this work with 1.1

The only other gradle plugin for robolectric (android-unit-test) has decided to deprecate that plugin, so currently *anyone* who uses Robolectric + gradle is stuck at plugin 1.0.1. If google comes along and decides to force people to use 1.1 (they have done it before) we are essentially screwed!

**Comment by jhansche** [comment]
Cross-linking the Google issue regarding `src/test/resources/` not added to the classpath: https://code.google.com/p/android/issues/detail?id=136013

Once that is fixed, the only change necessary would be to have some other way for the robolectric runtime to locate the manifest and resources.  One approach would be to set the `android.*` system properties directly on the test task(s):

    tasks.withType(Test).whenTaskAdded {
        it.systemProperty 'android.manifest', $pathToManifest
        // etc...
    }

but it would also be nice if the Google plugin could set that information, or expose it via some other runtime method.  That would be enough to remove the need for the robolectric-gradle-plugin entirely.

**Comment by erd** [comment]
I'm going to take a stab at updating our plugin this weekend to set the
system properties on the gradle tasks like you mentioned.

I doubt that the tools team would want to put that functionality in their
plugin. To be fair, it really doesn't belong in there.

**Comment by tallen1983** [comment]
Awesome! Going to try this on Monday. Will this allow running the tests inside Studio and on command line via Gradle?

**Comment by jhansche** [comment]
I tested today, and it works fine if you are only testing with the "debug" build type, and you have zero product flavors.  It does not work if you have a product flavor in your build (as "debug" is not a valid variant:  it would be instead "flavorDebug").  And it doesn't work if you want to test any non-Debug build type.

The Google issue linked above is also still an issue in 1.1.0-rc2:  src/test/resources files do not get added to the test classpath.

**Comment by erd** [comment]
> Will this allow running the tests inside Studio

It's not working in Studio at the moment. I need to do a little more research to figure out exactly what's wrong.

**Comment by tallen1983** [comment]
Inside Studio they don't use gradle to run the task from what I understand - so all of your configuration stuff may not be used. I recall seeing they have to wait for IntelliJ 14 integration to be able to do that.

It may be impossible for you to get it to work inside Studio without an IntelliJ plugin, similar to what android-unit-test gradle plugin and it's corresponding Studio plugin did.

**Comment by jhansche** [comment]
Does it work in Studio if you replace the JUnit configuration's "make" with "Gradle-aware make", as suggested on the Tools site?

**Comment by nenick** [comment]
@erd Did you try to run robolectric with just build in junit support? Here is an example which works with Android Studio https://github.com/nenick/AndroidStudioAndRobolectric without any extra plugins.

**Comment by xudshen** [comment]
@nenick quite useful example, thx...
