### ISSUE TITLE
robolectric-gradle-plugin conflicts with android-gradle-plugin:1.1.0-rc2

### ISSUE THREAD

**Issue by serj-lotutovici** [robolectric/robolectric-gradle-plugin#131]
When trying to update to android gradle plugin `1.1.0-rc2` the gradle sync fails because `testCompile` conflicts with the one defined in the android plugin.

Versions and Dependencies
* robolectric-gradle-plugin 0.14.1
* android-gradle-plugin 1.1.0-rc2
* org.robolectric:robolectric 2.4
* Android Studion 1.1 Beta 4

Error message: Error:(63, 0) Cannot add a configuration with name 'testCompile' as a configuration with that name already exists.

**Comment by JBirdVegas** [comment]
Seems Google's android plugin now attempting to handle junit tests.

http://tools.android.com/tech-docs/unit-testing-support

**Comment by erd** [comment]
See #129 & #130 - I'm working on making this plugin play nicely with the new unit test support.
