### ISSUE TITLE
incompatible to 1.1 android gradle plugin

### ISSUE THREAD

**Issue by rburgst** [robolectric/robolectric-gradle-plugin#135]
looks like issue #26 is back again:

        > No signature of method: com.android.build.gradle.AppPlugin.getBootClasspath() is applicable for argument types: () values: []

I have the following dependencies 

        classpath 'com.android.tools.build:gradle:1.1.0'
        classpath 'org.robolectric:robolectric-gradle-plugin:0.14.1'

**Comment by rburgst** [comment]
my bad, I had a different setup

**Comment by Stuie** [comment]
Just out of interest could you say how you fixed this in your project? I'm having the same issue and a quick Google search leads to here.

**Comment by rburgst** [comment]
I had a subproject that imported an older version.

**Comment by clocksmith** [comment]
I dont have a subproject with an older version (I don't think), and I am facing this issue
