### ISSUE TITLE
AndroidManifest.xml not found when using with Android Gradle plugin 1.1.0

### ISSUE THREAD

**Issue by denisk20** [robolectric/robolectric-gradle-plugin#142]
Hello,
I've been successfully using Robolectric with gradle with Android Gradle plugin 1.0.0 without robolectric plugin. However, after updating to 1.1.0 my tests are unable to find the manifest:

    WARNING: No manifest file found at ./AndroidManifest.xml. Falling back to the Android OS resources only.

Interesting thing that using both `@Config` and `org.robolectric.Config.properties` seem to be ineffective in solving it.
After incorporating your plugin into the project (with 1.1.0 plugin activated) the behavior of my test diverged. In the Android Studio I still get the same errors related to AndroidManifest.xml. When I run tests from console however I get `android.content.res.Resources$NotFoundException`.
I have 2 build types and 2 flavors. Tests are located under `src/test`. The manifest is under `src/main`. I have also tried to add a copy of the manifest just next to my test class, but to no avail.

I know that these issues are only partly related to the robolectric plugin itself, but would still appreciate any insights.

**Comment by erd** [comment]
The plugin does not work with Android Studio due to how studio runs tests.

With version 1.0.1 of the plugin, you shouldn't have to use @Config, Config.properties or any other configuration to run your tests on the command line.

**Comment by denisk20** [comment]
@erd Thanks for the clarification! Is there a chance that the plugin will work with Studio 1.2 (which is going to be based on IntelliJ 14) ?

**Comment by nenick** [comment]
This plugin works for me when using custom RobolectricTestRunner and provide the missing system properties.

    public class CustomRobolectricTestRunner extends RobolectricTestRunner {

      public CustomRobolectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
        String buildVariant = BuildConfig.BUILD_TYPE + (BuildConfig.FLAVOR.isEmpty()? "" : "/" + BuildConfig.FLAVOR);
        System.setProperty("android.package", BuildConfig.APPLICATION_ID);
        System.setProperty("android.manifest", "build/intermediates/manifests/full/" + buildVariant + "/AndroidManifest.xml");
        System.setProperty("android.resources", "build/intermediates/res/" + buildVariant);
        System.setProperty("android.assets", "build/intermediates/assets/" + buildVariant);
      }
    }

**Comment by denisk20** [comment]
@nenick Thanks, it works this way, just needed so swap build type and build flavor for build variant. Also checked your examples from https://github.com/nenick/AndroidStudioAndRobolectric, very useful.

**Comment by nealsanche** [comment]
@nenick Thanks, I also had to swap the build type and flavor, so my variant ended up looking like this:

```
import org.junit.runners.model.InitializationError;
import org.robolectric.RobolectricTestRunner;

public class CustomRobolectricTestRunner extends RobolectricTestRunner {

    public CustomRobolectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
        String buildVariant = (BuildConfig.FLAVOR.isEmpty() ? "" : BuildConfig.FLAVOR + "/") + BuildConfig.BUILD_TYPE;
        System.setProperty("android.package", BuildConfig.APPLICATION_ID);
        System.setProperty("android.manifest", "build/intermediates/manifests/full/" + buildVariant + "/AndroidManifest.xml");
        System.setProperty("android.resources", "build/intermediates/res/" + buildVariant);
        System.setProperty("android.assets", "build/intermediates/assets/" + buildVariant);
    }
}
```

**Comment by ypresto** [comment]
We have build flavors with different applicationIds (such like "com.example" and "com.example.development").
We also had to change from BuildConfig.APPLICATION_ID to default application id.

https://github.com/robolectric/robolectric-gradle-plugin/blob/master/src/main/groovy/org/robolectric/gradle/RobolectricPlugin.groovy#L24

``` java
public class CustomRobolectricTestRunner extends RobolectricTestRunner {
    public CustomRoblectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
        String buildVariant = (BuildConfig.FLAVOR.isEmpty() ? "" : BuildConfig.FLAVOR + "/") + BuildConfig.BUILD_TYPE;
        System.setProperty("android.package", BuildConfig.DEFAULT_APPLICATION_ID);
        System.setProperty("android.manifest", "build/intermediates/manifests/full/" + buildVariant + "/AndroidManifest.xml");
        System.setProperty("android.resources", "build/intermediates/res/" + buildVariant);
        System.setProperty("android.assets", "build/intermediates/assets/" + buildVariant);
    }
}
```

build.gradle:

``` groovy
def defaultApplicationId = "com.example"

android {
        applicationId defaultApplicationId
        buildConfigField "String", "DEFAULT_APPLICATION_ID", "\"${defaultApplicationId}\"" // for robolectric
        ...
}
```

(**EDITED**: at least with android gradle plugin 1.5.0, `"build/intermediates/res/"` must be `"build/intermediates/res/merged/"`)

**Comment by ypresto** [comment]
Above test runner works well on both Android Studio and Gradle test even without robolectric-gradle-plugin.

**Comment by DanielGrech** [comment]
For me the problem was because my class package (com.my.class.package) was different from my applicationId (com.my.app)

I fixed by adding `packageName = "com.my.class.package"` to my `@Config`

**Comment by xtien** [comment]
I had to add my build variant "app" to the string: "app/build/.... "

**Comment by davidgoli** [comment]
The current correct solution is to use the `RobolectricGradleTestRunner` like so:

``` java
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants=BuildConfig.class, sdk=21) // robolectric currently only supports up to API 21, sadly
public class CustomTest {
...
```

**Comment by chetbox** [comment]
I struggled with this for a while but eventually came up with a `RobolectricTestRunner` implementation that works for our setup:
- We have two flavours, `release` for production and `debug` for internal testing. The latter is what we test against.
- The `debug` flavour has an `applicationIdSuffix` of `.debug`

```java
public class RobolectricTestRunnerWithResources extends RobolectricTestRunner {

    @Override
    protected Config buildGlobalConfig() {
        return Config.Builder.defaults()
                .setPackageName("co.beeline")
                .setManifest("build/intermediates/manifests/full/debug/AndroidManifest.xml")
                .setResourceDir("../../../res/merged/debug") // relative to manifest
                .setAssetDir("../../../assets/debug") // relative to manifest
                .build();
    }

    public RobolectricTestRunnerWithResources(Class<?> testClass) throws InitializationError {
        super(testClass);
    }
}
```

**Comment by stanmots** [comment]
@chetbox How did you manage to set the manifest correctly? For me it just appends the given string to the default prefix so that the resulting path is 

` build/intermediates/bundles/debug/build/intermediates/manifests/full/debug/AndroidManifest.xml`

**Comment by chetbox** [comment]
This works for us. It might be that a different version of the Android SDK or Robolectric behave differently.

**Comment by IgorGanapolsky** [comment]
I am having the same issue as @storix.  My manifest path ends up being **build/intermediates/manifests/full/debug/build/intermediates/manifests/full/Beta/debug/AndroidManifest.xml**, which is wrong.  What is the fix?
