### ISSUE TITLE
Support Android Gradle plugin 1.2.x

### ISSUE THREAD

**Issue by Pombo** [robolectric/robolectric-gradle-plugin#148]
Hello,  
A new version of the Android Gradle plugin has been published ([1.2.1](https://bintray.com/android/android-tools/com.android.tools.build.gradle/view)) and according to the project site's changelog it mainly consist of bugfixes. Does anybody have info about a compatible release of the Robolectric Gradle plugin?
Hopefully it's only a matter of adding the supported version to the `SUPPORTED_ANDROID_VERSIONS` array.

thx

**Comment by erd** [comment]
Using Robolectric with Android Studio 1.1.0 doesn't require this plugin (and Robolectric 3.0 will make it significantly easier). I'm planning on deprecating this plugin when Robolectric 3.0 is released, so I'm hesitant to do any additional work on it.

**Comment by Pombo** [comment]
Oh ok I understand. But without the plugin is there a way to configure Robolectric (jvmArgs, maxHeapSize, ignoreFailures...) as it is done via the plugin? I'm particularly interested in passing arguments to the Robolectric JVM.

**Comment by jaredsburrows** [comment]
@erd  @Pombo So you can run Robolectric 3.0 tests via command line without the plugin?

**Comment by jaredsburrows** [comment]
Without using the plugin, upgrading to the Android Gradle plugin to `1.2.2`, running the tests from the command line do not work.

**Comment by jaredsburrows** [comment]
@erd Once again, @nenick to the rescue! 

Dependencies:

`classpath 'com.android.tools.build:gradle:1.2.2'`

        testCompile('org.robolectric:shadows-support-v4:3.0-rc2') {
            exclude group: 'commons-logging', module: 'commons-logging'
            exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        }

Command Line: `gradlew test`

    import org.junit.runners.model.InitializationError;
    import org.robolectric.RobolectricGradleTestRunner;
    import org.robolectric.annotation.Config;
    import org.robolectric.manifest.AndroidManifest;
    import org.robolectric.res.FileFsFile;
    import org.robolectric.res.FsFile;
    
    /**
    * More dynamic path resolution.
    *
    * This workaround is only for Mac Users necessary and only if they don't use the $MODULE_DIR$
    * workaround. Follow this issue at https://code.google.com/p/android/issues/detail?id=158015
    */
    public class CustomRobolectricRunner extends RobolectricGradleTestRunner {
    
        public CustomRobolectricRunner(Class<?> klass) throws InitializationError {
            super(klass);
        }
    
        protected AndroidManifest getAppManifest(Config config) {
            AndroidManifest appManifest = super.getAppManifest(config);
            FsFile androidManifestFile = appManifest.getAndroidManifestFile();
    
            if (androidManifestFile.exists()) {
                return appManifest;
            } else {
                String moduleRoot = getModuleRootPath(config);
                androidManifestFile = FileFsFile.from(moduleRoot, appManifest.getAndroidManifestFile().getPath().replace("bundles", "manifests/full"));
                FsFile resDirectory = FileFsFile.from(moduleRoot, appManifest.getResDirectory().getPath());
                FsFile assetsDirectory = FileFsFile.from(moduleRoot, appManifest.getAssetsDirectory().getPath());
                return new AndroidManifest(androidManifestFile, resDirectory, assetsDirectory);
            }
        }
    
        private String getModuleRootPath(Config config) {
            String moduleRoot = config.constants().getResource("").toString().replace("file:", "");
            return moduleRoot.substring(0, moduleRoot.indexOf("/build"));
        }
    }

*Source:* https://github.com/nenick/AndroidStudioAndRobolectric/blob/master/app/src/test/java/com/example/myapplication/CustomRobolectricRunner.java

**Comment by Pombo** [comment]
@jaredsburrows Yes I managed to run my tests via command line without the plugin. Both with Robolectric 2.3 and 3.0 actually.

In my project I'm currently required to stay with **Robolectric 2.3** but I need the Android plugin 1.2.0 because of the bugfixes regarding the unit tests. Moreover I need to pass a gradle property to my RobolectricTestRunner to do some configuration. Up until now, I could do it thanks to the Robolectric plugin with `robolectric { jvmArgs '-Dmy.parameter='.concat(myParameter) }`. But I found a way to do that without the plugin.

- With `Robolectric 2.3` and the `Android plugin 1.2.0` : 
 
**build.gradle**

```groovy
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.0'
    }
}
...
android {
    ...

    libraryVariants.all { variant ->
        def task = project.tasks.findByName("test${variant.name.capitalize()}")
        task.systemProperty("android.assets", variant.mergeAssets.outputDir)
        task.systemProperty("android.manifest", variant.outputs.first().processManifest.manifestOutputFile)
        task.systemProperty("android.resources", variant.mergeResources.outputDir)
        task.systemProperty("android.package", project.android.defaultConfig.applicationId)
        task.systemProperty("my.parameter", myParameter)
    }
}

dependencies {
    testCompile 'junit:junit:4.12'
    testCompile('org.robolectric:robolectric:2.3') {
        ...
    }

    ...
}
```

**MyRobolectricTestRunner.java**

```java
public class MyRobolectricTestRunner extends RobolectricTestRunner {

    public MyRobolectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    protected void configureMaven(DependenciesTask dependenciesTask) {
        String myParameter = System.getProperty("my.parameter")
        ...
    }
}
```


- With `Robolectric 3.0-rc2` and the `Android plugin 1.2.0` :  

 **build.gradle**

```groovy
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:1.2.0'
    }
}
...
android {
    ...

    libraryVariants.all { variant ->
        def task = project.tasks.findByName("test${variant.name.capitalize()}")
        task.systemProperty("my.parameter", myParameter)
    }
}

dependencies {
    testCompile 'junit:junit:4.12'
    testCompile('org.robolectric:robolectric:3.0-rc2') {
        ...
    }
    testCompile 'org.apache.maven:maven-ant-tasks:2.1.3'

    ...
}
```

**MyRobolectricTestRunner.java**

```java
public class MyRobolectricTestRunner extends RobolectricGradleTestRunner {

    public MyRobolectricTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    @Override
    protected DependencyResolver getJarResolver() {
        return new MyMavenDependencyResolver();
    }

    private class MyMavenDependencyResolver extends MavenDependencyResolver {

        @Override
        protected void configureMaven(DependenciesTask dependenciesTask) {
            String myParameter = System.getProperty("my.parameter")
            ...
        }
    }
}
```

**Comment by jaredsburrows** [comment]
@Pombo Very nice! So can we close this issue?

Also, why are you using Robolectric `2.3`? At least use Robolectric `2.4`.

**Comment by Pombo** [comment]
@jaredsburrows the project was simply started with `2.3` :D I guess we're going to jump from Robolectric `2.3` to `3.0`.

**Comment by jaredsburrows** [comment]
@Pombo Well, you can atlas use `2.4`, there shouldn't be any issues. When you make the upgrade, use @nenick's https://github.com/nenick/AndroidStudioAndRobolectric/blob/master/app/src/test/java/com/example/myapplication/CustomRobolectricRunner.java and https://github.com/robolectric/robolectric/wiki/2.4-to-3.0-Upgrade-Guide. @erd I added the custom runner to that page, but someone remove all my revisions.

**Comment by erd** [comment]
The custom runner isn't needed since `RobolectricGradleTestRunner` will be bundled in 3.0.

**Comment by jaredsburrows** [comment]
Yeah but @nenick's custom runner extends `RobolectricGradleTestRunner` and helps with the `android.content.res.Resources$NotFoundException:`. Are you saying `RobolectricGradleTestRunner` does not need to be extended for this to work?

**Comment by erd** [comment]
Yes

**Comment by jaredsburrows** [comment]
Alright thanks. I guess you do not need @nenicks CustomRobolectric runner. It seems to work fine without it as well.

**Comment by nenick** [comment]
@erd would be nice to have a new release candidate ;)

**Comment by jaredsburrows** [comment]
+1

**Comment by mag** [comment]
+1
