### ISSUE TITLE
Error:Cannot invoke method systemProperty() on null object

### ISSUE THREAD

**Issue by anivaler** [robolectric/robolectric-gradle-plugin#161]
Hi, I have this error:
"Error:Cannot invoke method systemProperty() on null object"

Android Studio 1.3.2

I've tried integrate Linkedin SDK and sdk contains robolectric dependencies.

build.gradle in Linkedin library:

allprojects {
    repositories {
        mavenCentral()
    }
}

buildscript {
   repositories {
     mavenCentral()
   }

   dependencies {
     classpath 'org.robolectric:robolectric-gradle-plugin:1.0.0'
   }
}

apply plugin: 'android-library'
apply plugin: 'org.robolectric'

android {
    sourceSets {
        androidTest {
         setRoot('src/test')
        }
    }
    compileSdkVersion 17 
    buildToolsVersion "19.1.0"

```
defaultConfig {
    minSdkVersion 8
    targetSdkVersion 16 
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

configurations {
}

robolectric {
  include '*_/_Test.class'
}

dependencies {
    compile 'com.android.support:support-annotations:20.0.0'
    compile 'com.android.support:support-v4:21.0.+'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile files('libs/volley.jar')
    androidTestCompile('junit:junit:4.12')
    androidTestCompile('org.robolectric:robolectric:2.4')
}

Thanks in advance.

**Comment by erd** [comment]
This plugin is no longer being maintained.

**Comment by anivaler** [comment]
But how can I resolve this issue?
