### ISSUE TITLE
esri mapview shown Black in mobile . Rendering problem 

### ISSUE THREAD

**Issue by temorh** [robolectric/robolectric-gradle-plugin#163]
i have a probleme using mapview for android studio when i **update to last version both android and sdk** 
the map cannot be rendered and it shown black in startup . pls can any body help me !!!

- **# com.esri.arcgisruntime.mapping.view.MapView** (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  
If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details 
java.lang.VerifyError: # **Expecting a stackmap frame at branch target 19** Exception Details: 
Location: 
com/esri/arcgisruntime/mapping/view/GeoView. (Landroid/content/Context;Landroid/util/AttributeSet;)V @10: ifeq Reason: Expected stackmap frame at this location. Bytecode: 0x0000000: 2a2b 2cb7 001d 2ab6 0021 9900 092a 01b5 0x0000010: 0023 b1b1    at java.lang.Class.getDeclaredConstructors0(Class.java:-2)   at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)   at java.lang.Class.getConstructor0(Class.java:3075)   at java.lang.Class.getConstructor(Class.java:1825)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)

**Comment by rongwei84n** [comment]
it looks like issue 144
https://github.com/robolectric/robolectric-gradle-plugin/issues/144

**Comment by temorh** [comment]
Thxi fixed it before 2 months i think 😉

On Thursday, May 18, 2017, rongwei84n <notifications@github.com> wrote:
> it looks like issue 144
> #144
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/gQZ8RjZ5gjDYF2qS94MdtUIJd-2gTLMR41BDLWwf_ay-Uzozz66rAzv8NWijmrP92WbKA_VdD6YgerUahtnOYwXxObDmRnNZQqadgB1CGQT3EO1rDoj8xBXAqugPZYTrcflfG3BJuRfUhgAWyGMsaRTqwJssEA=s0-d-e1-ft#https://github.com/notifications/beacon/AP4jP5U5e7_CtOaWKwQSkFENTqotTov0ks5r694RgaJpZM4Lmnu_.gif>

**Comment by utzcoz** [comment]
Looks like this issue was fixed. So I will close this issue.
