### ISSUE TITLE
Leveraging androidTestCompile as the configuration results in unnecessary jars on the classpath

### ISSUE THREAD

**Issue by battags** [robolectric/robolectric-gradle-plugin#37]
I was using the previous iteration of this plugin (on Gradle Android Plugin 0.9.x) and have attempted to upgrade to leverage the latest Gradle plugin.

In the previous iteration of the plugin, there was a "testCompile" configuration which kept the classpath separate from the instrumentation test classpath.  The new version does not appear to keep that separation.

That appears to cause some problems.  For example, for "instrumentation tests" (androidTest) we need to define "dexmaker-mockito" as a dependency in order to have proper Mockito support in android tests.  However, for simple unit tests this is not needed and actually causes problems (null pointer exceptions, forcing the addition of the dexcache system property, etc.) when included, meaning one can either have unit tests or android tests, but not both (at least as far as I can tell).

Is there (a) a work-around I am missing or (b) a plan to separate these configurations again?

**Comment by erd** [comment]
With #129, we piggyback on the Android Gradle plugin's support for unit tests (which has a separate scope for unit tests and integration tests).
