### ISSUE TITLE
Support for Gradle Plugin Portal

### ISSUE THREAD

**Issue by ChristianBecker** [robolectric/robolectric-gradle-plugin#45]
It would be nice if the robolectric-gradle-plugin would be available in the new Gradle Plugin Portal (Announcement: http://www.gradleware.com/uncategorized/new-gradle-plugin-portal/). As of Gradle 2.1 (I know, it is not released nor supported yet) you could then apply the plugin with:
```
plugins {
    id "org.robolectric.gradle" version "0.11.+"
}
```

A guideline for plugin submitting is available at: http://plugins.gradle.org/submit

**Comment by erd** [comment]
The plugin is being deprecated with the release of Robolectric 3.0. Closing open issues.
