### ISSUE TITLE
NullPointerException when loading AndroidManifest.xml with google_play_services_version meta-data entry

### ISSUE THREAD

**Issue by pjk25** [robolectric/robolectric-gradle-plugin#56]
Myself and @erictsiliacos are running into an issue with resource loading and Robolectric with Gradle.  On the command line, the AndroidManifest.xml is discovered automatically, but the resources directory is not.  When running in Intellij, neither are properly discovered.  It appears to be related to https://github.com/robolectric/robolectric/issues/1025 on Robolectric.

We see the issue with Robolectric 2.3, 2.4-SNAPSHOT, and the Android gradle plugin 0.11.+ and 0.12.+.

We found that explicitly setting the locations allowed us to successfully run tests in both environments:
````@Config(manifest = "build/intermediates/manifests/debug/AndroidManifest.xml", resourceDir = "../../../../build/intermediates/res/debug", emulateSdk = 18)````

We were pointed to https://github.com/robolectric/robolectric-gradle-plugin/issues/52, and found that specifying the applicationId allowed tests to run on the command line with simply ````@Config(emulateSdk = 18)````, however the full config was still needed to run tests inside of Intellij.

It seems like it should be unnecessary to specify these paths, given that our project is using the standard android gradle directory structure.  Is there some other preferred way of configuring this, or is possibly a bug in test environment generated by the robolectric-gradle-plugin?

**Comment by erd** [comment]
This should be fixed in #129, since we rely on the Android Gradle plugin to merge resources before running tests, which should merge library resources into the app's resources.
