### ISSUE TITLE
Robolectric + JUnit test case written in Scala doesn't work

### ISSUE THREAD

**Issue by oskargargas** [robolectric/robolectric-gradle-plugin#75]
Hey, I use your plugin with `p.leafytree.gradle:gradle-android-scala-plugin`. It looks like `gradle clean test` doesn't try to compile nor use test code I write in Scala and put in `src/androidTest/scala`.

I've managed to run JUnit + Robolectric tests written in Java, simple, but my goal is to write them in Scala. At least pure JUnit + Robolectric but in Scala. In better world I'd use [ScalaTest Matchers](http://www.scalatest.org/getting_started_with_junit_4_in_scala) and in perfect world I'd use ScalaTest instead of JUnit but lets start simple. 

I want to run this test case with all my Java JUnit test cases:

    @RunWith(classOf[RobolectricTestRunner])
    class PureJUnitScalaTest {
      @Test def sampleTest(): Unit = {
        assertThat(10, is(10))
      }
    }

I attach my [test project](https://dl.dropboxusercontent.com/u/4536220/Test_AS.zip) with whole gradle configuration and source code.

I'm not exactly sure if this is problem with `robolectric-gradle-plugin` but I hope you can help me.

**Comment by BobReid** [comment]
Same issue for Kotlin. The robolectric test tasks don't seem to be triggering the compile${variant}TestKotlin tasks so the kotlin classes are never built and do not end up in the test-classes folder. If i manually run the task and copy the .class files into the test-classes folder robolectric runner has no problem executing them. 

Hooking into the plugin to support other JVM languages would be pretty sweet.

**Comment by BobReid** [comment]
I got robolectric running my tests written in Kotlin with the following tweaks to the gradle file
```
task copyKotlinTestFiles(type: Copy) {
    inputs.dir('build/intermediates/classes/test/debug')
    outputs.dir('build/test-classes')

    from fileTree('build/intermediates/classes/test/debug')
    into 'build/test-classes'
}

gradle.projectsEvaluated {
    copyKotlinTestFiles.dependsOn(compileDebugTestKotlin)
    testDebug.dependsOn(copyKotlinTestFiles)
}
```

**Comment by erd** [comment]
#129 changed the implementation significantly so we piggy-back on the unit testing support added in version 1.1.0 of the Android Gradle plugin. Can you retest with 1.0.0-SNAPSHOT? If it doesn't work, we may not be able to support this feature since I'd like to not have a ton of custom build logic in this plugin.

**Comment by asarazan** [comment]
Any chance we can get this reopened, or some guidance as to what to request of the Kotlin team (assuming this is something they can fix)?

At the moment all alternative JVM languages are locked out of Robolectric testing, which is a shame because that's where Kotlin's DSL capabilities really shine.

**Comment by erd** [comment]
I don't use Scala or Kotlin, so I'm not sure where to start to address the issue. For what it's worth, Robolectric 3.0 + Android Studio 1.1.0 doesn't require this plugin to run, so we'll be deprecating it once 3.0 is released.
