### ISSUE TITLE
Executing tests fails randomly

### ISSUE THREAD

**Issue by weiznich** [robolectric/robolectric-gradle-plugin#78]
Tried to execute my robolectric tests throught gradle, but on a randomly test execution is stopped and gradle fails. Any idea whats causing this and how to solve this?

[Stacktrace](http://zero.azapps.de/?4282f06329bee9c5#M6LwWEODwioGEonOsS8yB3iv003EXYd3UGVck1rLXd4=)

**Comment by weiznich** [comment]
[Stacktrace](http://zero.azapps.de/?7914b8f942d22ed8#spIPzk90VxhkehADFlusg8o0oaldCNPuK1zeQjvBXqc=)
[Codebase](https://github.com/MirakelX/mirakel-android/)
[Needed patchset](https://gerrit.azapps.de/r/#/c/2070/)

**Comment by weiznich** [comment]
[another stacktrace](http://zero.azapps.de/?31fc4472197b8b2b#96XdL+5FkaKPXT+FegVzXFGyTdczmPzINB6Aew35ZgE=)

**Comment by erd** [comment]
I suspect that this is fixed with #129 since we rely on the Android Gradle plugin to build and run our tests (this plugin just sets up the necessary system properties to run Robolectric).
