### ISSUE TITLE
Can't read org.robolectric.Config.properties file

### ISSUE THREAD

**Issue by pjakubczyk** [robolectric/robolectric-gradle-plugin#80]
First, thanks for plugin! Robolectric provides handy interface for global configuration for custom Shadow classes (http://robolectric.org/configuring/).

Doest the plugin supports the same structure? Where should I put the 'resources' directory?

**Comment by nishantsoni** [comment]
I overrode getConfigProperties() by subclassing RobolectricTestRunner. Please follow this link: http://stackoverflow.com/a/29907234/727654
